---
- import_tasks: update.yml

# Interface grafica
- import_tasks: gui.yml
  when: proaluno_install_gui

#- import_tasks: pacotes_debian.yml
#  when: proaluno_install_pacotes_debian


#- import_tasks: reboot.yml
#- import_tasks: conky.yml

# Scripts chamados por outras tarefas
- import_tasks: scripts.yml

# Lightdm, para gerenciamento de ambiente
- import_tasks: lightdm.yml

# Impede o desligamento do pc via interface 
- import_tasks: restrict_shutdown.yml


# Impede o bloqueio de tela
# No XFCE, esta disponivel o light-locker
- import_tasks: disable_screenlock.yml
  when: proaluno_gui == "xfce"

# Noutros casos, o {gui}-screensaver eh utilizado
- import_tasks: remove_screensaver.yml
  when: proaluno_gui != "xfce"


#- import_tasks: make_ssh_folder.yml
#- import_tasks: firefox.yml

# gis versão mais nova
#- import_tasks: qgis.yml

#- import_tasks: update_keys.yml
#  when: proaluno_update_keys

#- import_tasks: home.yml
#- import_tasks: presamba.yml

#- import_tasks: external_roles.yml






