- name: Instalação de pacotes mate
  apt:
    pkg:
      - task-mate-desktop
      - mate-desktop-environment
      - mate-menu
      - dconf-cli

- name: Remove screensaver - para não entrar em tela de descanso
  apt:
    name: "mate-screensaver"
    state: absent
    purge: yes

- name: Remove screensaver - para não entrar em tela de descanso
  apt:
    name: "mate-screensaver-common"
    state: absent
    purge: yes

- name: Copy /etc/skel/.config
  copy:
    src: files/mate/dot_config/
    dest: /etc/skel/.config
    mode: '0755'

- name: create /etc/skel/ folders
  file:
    path: "/etc/skel/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - 'Área de trabalho'
    - 'Documentos'
    - 'Downloads'
    - 'Imagens'
    - 'Vídeos'
    - 'Música'
    - 'Público'
    - 'Modelos'

# TODO: Verificar como configurar o toolbar do cinnamom
- name: Copy /proaluno/dconf-dump.ini
  copy:
    src: files/dconf-dump.ini
    dest: /proaluno/dconf-dump.ini
    mode: '0755'

- name: Foto de background padrão para todos usuários
  copy:
    src: files/fflch.png
    dest: /proaluno/fflch.png
    mode: '0755'

- name: Definição da foto background padrão para todos usuários 10dconf_override
  copy:
    src: files/10dconf_override
    dest: /etc/X11/Xsession.d/10dconf_override
    mode: '0644'