- name: Instalação de pacotes via apt
  apt:
    pkg: 
      - kolourpaint
      - firmware-linux-nonfree
      - webext-ublock-origin
      - ntfs-3g
      - dosfstools
      - exfat-fuse
      - exfat-utils
      - chromium
      - nomacs
      - vim
      - fonts-crosextra-carlito
      - fonts-crosextra-caladea
      - ttf-mscorefonts-installer
      - p7zip-full
      - p7zip-rar
      - gvfs-backends # para celulares
      - gnome-disk-utility
      - zip
      - unzip
      - rar
      - unrar
      - pdftk
      
# Avaliar se precisamos desses pacotes:
#      - texlive-full
#      - texstudio-l10n 
#      - praat
#      - texstudio
#      - inkscape
#      - gimp
#      - gimp-help-pt
#      - build-essential
#      - r-base
#      - gfortran
#      - terminator
#      - okular
#      - audacity
#      - vlc
#      - git
- name: cmprescott.chrome
  include_role:
    name: cmprescott.chrome
