# https://wiki.debian.org/SystemPrinting
- name: Install a printers list of packages
  apt:
    pkg:
    - cups
    - printer-driver-all
    - foomatic-db-engine
    - hp-ppd
    - openprinting-ppds
    - cups-tea4cups

- name: Create a directory /usr/lib/cups/filter
  file:
    path: /usr/lib/cups/filter
    state: directory
    mode: '0755'

- name: Copy gstopdf17
  copy:
    src: files/gstopdf17
    dest: /usr/lib/cups/filter/gstopdf17
    mode: '0755'

- name: Copy gstopdf14
  copy:
    src: files/gstopdf14
    dest: /usr/lib/cups/filter/gstopdf14
    mode: '0755'

- name: Copy lpoptions
  copy:
    src: files/lpoptions
    dest: /etc/cups/lpoptions
    mode: '0644'

- name: Copy ppds
  copy:
    src: "files/ppds/{{item}}"
    dest: "/usr/share/cups/model/{{item}}"
    mode: '0755'
  loop:
    - K7600_direto.ppd
    - K7600_processado_gstopdf14.ppd
    - K7600_processado_gstopdf17.ppd

#### remover impressoras antes de instalar a nova
# Comando para fazer a remoção na mão:
# for i in $(lpstat -p | awk '{print $2}'); do lpadmin -x $i; done
- name: getting installed printers
  shell: lpstat -p | awk '{print $2}'
  register: installed_printers

- name: Initialize an empty list for our printer_to_keep
  set_fact:
    printers_to_keep: []

- name: Append string to list
  set_fact:
    printers_to_keep: "{{ printers_to_keep + [item.name] }}"
  loop: "{{ proaluno_printers }}"

- name: removing all installed printers
  shell: lpadmin -x {{ item }}
  loop: "{{ installed_printers.stdout_lines }}"
  when: proaluno_remove_all_printers
  ignore_errors: True

- name: removing older printers
  shell: lpadmin -x {{ item }}
  loop: "{{ installed_printers.stdout_lines }}"
  when:
    - item not in printers_to_keep
    - not proaluno_remove_all_printers
  ignore_errors: True

#### Instalação das impressoras
#    -v tea4cups:{{ item.device }}
#- name: Install printers
#  shell: >
#    /usr/sbin/lpadmin -p {{ item.name }}
#    -v {{ item.device }}
#    -m {{ item.model }}
#    -o printer-error-policy=abort-job
#    -o printer-is-shared=false
#    -o sides=two-sided-long-edge
#    -o Media=A4
#    -o PageSize=A4
#    - -E

# lpadmin -E option forces encryption when connecting to the server
  args:
    chdir: /usr/share/cups/model
  loop: "{{ proaluno_printers }}"

- name: Disable services
  systemd:
    name: "{{item}}"
    state: stopped
    enabled: no
    masked: yes
  loop:
    - cups-browsed
#    - avahi-daemon

- name: Remove avahi-daemon
  apt:
    name: "avahi-daemon"
    state: absent
    purge: yes

- name: Copy cupsd.conf
  template:
    src: templates/cupsd.conf
    dest: '/etc/cups/cupsd.conf'
    mode: '0644'

############# tea4cups
- name: create /proaluno folder
  file:
    path: /proaluno
    state: directory
    mode: '0755'

- name: Copy dialog_tea4cups.sh
  template:
    src: templates/dialog_tea4cups.sh
    dest: '/proaluno/dialog_tea4cups.sh'
    mode: '0755'

- name: Copy dialog_tea4cups.sh
  template:
    src: templates/dialog_tea4cups_post.sh
    dest: '/proaluno/dialog_tea4cups_post.sh'
    mode: '0755'

- name: pre hook cups to open dialog
  lineinfile:
    path: '/etc/cups/tea4cups.conf'
    regexp: '^prehook_open_check_quotas'
    state: present
    create: yes
    line: 'prehook_open_check_quotas : /proaluno/dialog_tea4cups.sh'

- name: post hook cups to open dialog
  lineinfile:
    path: '/etc/cups/tea4cups.conf'
    regexp: '^posthook_dialog'
    state: present
    create: yes
    line: 'posthook_dialog : /proaluno/dialog_tea4cups_post.sh'
